# Generated by Django 4.0.2 on 2022-02-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_address_options_alter_address_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Profiles'},
        ),
    ]
