# Generated by Django 4.0.2 on 2022-02-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='saved',
        ),
    ]
