# Generated by Django 4.0.2 on 2022-02-28 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='book_format',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='product',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='signed_copy',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('author', models.CharField(blank=True, max_length=254, null=True)),
                ('release_date', models.CharField(blank=True, max_length=254, null=True)),
                ('signed_copy', models.CharField(blank=True, max_length=254, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='BoxedSet',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('release_date', models.CharField(blank=True, max_length=254, null=True)),
                ('signed_copy', models.CharField(blank=True, max_length=254, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Collectible',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('release_date', models.CharField(blank=True, max_length=254, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=254, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            bases=('products.product',),
        ),
    ]
